### ISSUE TITLE
Add a way to remove labels

### ISSUE THREAD

**Issue by marcofugaro** [actions-ecosystem/action-add-labels#275]
## What you want to add

I am running this actions on `edited` as well

```yml
on:
  issue:
    types: [opened, edited]
```

So if someone remove the `/add-labels` comment from `github.event.comment.body`, I want the related label to be removed.

How do I do that?

## Why this is needed

I am using this action to mark a PR as `WIP` or not `WIP`.
