### ISSUE TITLE
Add Usage Example

### ISSUE THREAD

**Issue by jackwener** [actions-ecosystem/action-add-labels#333]
## What you want to add

I have tried to add it in my test repo. It didn't work.

It will be better to add Usage Example

## Why this is needed

Help user to use this action

**Comment by jackwener** [comment]
It didn't work. like those.

[Test PR](https://github.com/jackwener/Readings-in-Database-Systems-5th-CN/pull/14)

[Test issue](https://github.com/jackwener/Readings-in-Database-Systems-5th-CN/issues/15)

**Comment by jackwener** [comment]
The current way of using it is like touching the elephant by the blind, I think it’s not very good

**Comment by jackwener** [comment]
action-add-lable didn't work. [link](https://github.com/jackwener/Readings-in-Database-Systems-5th-CN/runs/4724473369?check_suite_focus=true)

**Comment by liangyuanpeng** [comment]
```
name: Add Label

on:
  issue_comment:
    types: [created, deleted]
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: bug
```

This is the example for add label when you create a issue .

Github-Action bot will add label "bug" when you add a comment to issue and comment startwith '/add-labels'.
