### ISSUE TITLE
[NOT WORKING] if: ${{ startsWith(github.event.comment.body, '/add-labels') }}

### ISSUE THREAD

**Issue by ojedavidea** [actions-ecosystem/action-add-labels#63]
Hello, I have tried this

```
name: Add Labels

on:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            documentation
            changelog
```

with this

```
name: splitter

on:
  pull_request:

jobs:
  splitter1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dispatcher 1
      run: |
        line=$(tail -n 2 0/1)
        SUB="name: Octocat"
        if grep -q "$SUB" <<< "$line";
        then
           echo "NEXTEP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"milestone": 1}'
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "1" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "/add-labels"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "second comment"}'
        else
           echo "FLIP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "-1" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus first comment"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus second comment"}'
           exit 1
        fi
```

In order to add multiple labels after someone has commited a pull-request and before it is merged. As I think it is supposed to work I added this line: `--data '{"body": "/add-labels"}'` which is supposed to answer to this line: if: `${{ startsWith(github.event.comment.body, '/add-labels') }}` but it seems it did not work and that I have done something wrong or something in the code was wrong.

**Comment by micnncim** [comment]
Hi @ojedavidea,

Thank you for your report.

It's **NOT** a bug. GitHub Actions doesn't trigger events dispatched by GitHub Actions. You would be able to realize your workflows with [repository_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) as one of the methods.

**Comment by ojedavidea** [comment]
So I guess the correct version of your code if you want to multi-label (`documentation` and `changelog`) upon commenting (`/add-labels`) with GitHub Actions would be:

```
name: Add Labels

on:
  issue_comment:
    types: [created]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            documentation
            changelog
```
